name: Context Example Workflow

on:
  workflow_dispatch:

jobs:
  context-example:
    runs-on: ubuntu-latest
    steps:
      - name: Display context information
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
