name: context workflow

on:
  push:
    branches:
      - feature

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "context"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display context information
        run: |
          echo "Commit SHA: ${{ github.sha }}"
          echo "Branch: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Environment Variable: ${{ env.MY_VAR }}"
