name: Filter Workflow

on:
  push:
    branches-ignore:
      - dev
jobs:
  filter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Display commits
        run: echo "This workflow passed the filters"
