name: Filter Workflow with Tags

on:
  push:
    branches:
      - main
    tags:
      - 'v1.*'
    tags-ignore:
      - 'test-*'

jobs:
  filter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Display commits
        run: echo "This workflow passed the tag filters"
