name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  manual-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Display message
        run: echo "This workflow was triggered manually"
